server {
    listen 443 ssl;
    http2 on;
    server_name drongier.42.fr;
    
    # Certificats SSL
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    
    # Racine et index
    root /var/www/html;
    index index.php index.html index.htm;
    
    # Gestion des URLs WordPress
    location / {
        try_files $uri $uri/ /index.php?$args;
    }
    
    # Gestion des fichiers PHP
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
