version: '3.8'

services:
  mariadb:
    build: ./srcs/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  nginx:
    build: ./srcs/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/${USER}/data/mariadb

networks:
  inception:
    driver: bridge
